addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - libxml2-utils
      - wget
      # Package list from http://bazel.io/docs/install.html
      - pkg-config
      - zip
      - unzip
      - zlib1g-dev
jdk:
  - oraclejdk8

before_install:
  - wget 'https://github.com/bazelbuild/bazel/releases/download/0.3.1/bazel-0.3.1-installer-linux-x86_64.sh'
  - sha256sum -c .bazel-installer-linux-x86_64.sh.sha256
  - chmod +x bazel-0.3.1-installer-linux-x86_64.sh
  - ./bazel-0.3.1-installer-linux-x86_64.sh --user
  - mv .bazelrc.travis .bazelrc

script:
  - bash test_run.sh
